### ISSUE TITLE
🛠️ Repo: Selenium failures in CI: headless is not a function

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha-examples#88]
Example from https://github.com/mochajs/mocha-examples/actions/runs/9796439260/job/27050896587?pr=87:

```plaintext
example-selenium-app:  Exception during run: TypeError: (intermediate value).headless is not a function
example-selenium-app:     at Object.<anonymous> (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/test/selenium.spec.js:7:44)
example-selenium-app:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
example-selenium-app:     at Module._compile (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/pirates/lib/index.js:117:24)
example-selenium-app:     at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
example-selenium-app:     at Object.newLoader [as .js] (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/pirates/lib/index.js:121:7)
example-selenium-app:     at Module.load (node:internal/modules/cjs/loader:1076:32)
example-selenium-app:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
example-selenium-app:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
example-selenium-app:     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
example-selenium-app:     at async Promise.all (index 0)
example-selenium-app:     at ESMLoader.import (node:internal/modules/esm/loader:530:24)
example-selenium-app:     at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
example-selenium-app:     at formattedImport (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
example-selenium-app:     at Object.exports.requireOrImport (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
example-selenium-app:     at Object.exports.loadFilesAsync (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
example-selenium-app:     at singleRun (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/mocha/lib/cli/run-helpers.js:158:3)
example-selenium-app:     at Object.exports.handler (/home/runner/work/mocha-examples/mocha-examples/packages/selenium/node_modules/mocha/lib/cli/run.js:370:5)
lerna ERR! npm run test exited 1 in 'example-selenium-app'
```

**Comment by JoshuaKGoldberg** [comment]
TIL https://www.selenium.dev/blog/2023/headless-is-going-away ✨
